FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ECFA Data Endpoint API

This API is used by Fraud Analyzer client to store/retrieve information about orders.

## HTTPs Request

Every request should be made to the endpoint `https://api.ecfa-project.space/{resource}`, where `resource`
refers to the resource target. Currently, `resource` only accepts `orders`.

**Note that the request should be made via HTTPs protocol**

Allowed HTTPs request:
- `POST` - Create or update a resource
- `PUT` - Update a resource
- `GET` - Retrieve a resource

Note that requests made using `PUT` can also be done using `POST`, unless the reference below says otherwise.

## API Authorization

You should have had the API Token and Secret in order to be able to communicate with the API endpoint.
Both Token and Secret will be used to make the Basic Authorization header which will look like this:

```javascript
Authorization: Basic Base64-of-token:secret
```

For example, if you have API Token `pakkadim` and API Secret `midakkap`, every request's header
to API endpoint should include

```javascript
Authorization: Basic cGFra2FkaW06bWlkYWtrYXA
```

Notice that `cGFra2FkaW06bWlkYWtrYXA` is the output of `Base64(pakkadim:midakkap)`.

Any request made without specifying the authorization header will be responded with `403` error.

## Notes on API Authorization

If your API Token and Secret are exposed to the public, it should be considered to generate new
API Token and Secret as any adversary knowing the API Token and Secret may use masquerade attacks,
breaching the access to the data stored on the server.


## Order/Entry [/orders]

### Get Orders [GET]

+ Request (application/json)
    + Headers
        
            Accept: application/json
            Authorization: Basic base64-of-token:secret
    
    + Attributes (array)
        + order_id - Order/entry ID
    
    + Body
    
            ["A151003"]

+ Response 200 (application/json)

    + Attributes (array[ECFAOrder])
    
    + Body

            [
                {
                    "order_id": "A151003",
                    "fraud_percentage": 25
                }
            ]

### Store Orders [POST]

+ Request (application/json)
    + Headers
        
            Accept: application/json
            Authorization: Basic base64-of-token:secret
        
    + Attributes (array[Order])

    + Body
    
            [
                {
                    "order_id": "A151003"
                }
            ]

+ Response 201 (application/json)
    + Attributes (CreationUpdateResponse)
    
    + Body
    
            {
                "code": 201,
                successful_ids: [
                    "A151003"
                ],
                unsuccessful_ids: [
                    "B151003"
                ]
            }

+ Response 401 (application/json)
    + Attributes (UnauthorizedResponse)
    
    + Body
    
            {
                "code": 403,
                "message": "Authorization header not found or invalid."
            }

### Update Orders [PUT]

Note that this API request acts the same with the `POST` one, except that this one will only return `200` if all
of the identifiers are found in the server.

+ Request (application/json)
    + Headers
        
            Accept: application/json
            Authorization: Basic base64-of-token:secret
        
    + Attributes (array[Order])

    + Body
    
            [
                {
                    "order_id": "A151003"
                }
            ]

+ Response 201 (application/json)
    + Attributes (CreationUpdateResponse)
    
    + Body
    
            {
                "code": 201,
                successful_ids: [
                    "A151003"
                ],
                unsuccessful_ids: [
                    "B151003"
                ]
            }

+ Response 401 (application/json)
    + Attributes (UnauthorizedResponse)
    
    + Body
    
            {
                "code": 403,
                "message": "Authorization header not found or invalid."
            }

## Single Order/ Entry [/orders/{order_id}]

+ Parameters
    + order_id (string) - ID of the order in the form of an integer / objectID 

### Get an Order [GET]
+ Request 
    + Headers
        
            Authorization: Basic base64-of-token:secret

    
+ Response 200 (application/json)

    + Body

            {
                "order_id": "A151003",
                "fraud_percentage": 25
                "status" : "accepted"
                "timestamp" : "2016-01-15 12:13:14" 
            }

+ Request(application/json)
    
    + Headers
    
            Accept: application/json
            Authorization: Basic base64-of-token:secret
    
    + Body
    
            {
                "id" : "A151003"
                "user_id" : "123ECFA123"
                "start_date" : "2016-01-15"
                "end_date" : "2016-01-16"
            }

+ Response 200(application/json)

    + Attributes (array[Order])
    
    + Body
    
            [
                {
                    "order_id": "A151003",
                    "fraud_percentage": 25
                    "status" : "accepted"
                    "timestamp" : "2016-01-15 12:13:14"        
                },
                {
                    "order_id": "A151004",
                    "fraud_percentage": 90
                    "status" : "rejected"
                    "timestamp" : "2016-01-16 12:13:14"
                }
            ]

### Store an Order [POST]

+ Request (application/json)
    + Headers
        
            Accept: application/json
            Authorization: Basic base64-of-token:secret

    + Body
    
            {
                "id" : "String"
                "item_total" : "Float"
                "total" : "FLoat"
                "adjustment_total" : "Float"
                "user": "ilham1"
                "user_verified": "Boolean"
                "total_quantity": "5"
                "created_at" : "2016-01-15 10:13:14"
                "updated_at" : "2016-01-15 12:13:14"
                "payment_total" : "Float"
                "payment_state" : "String"
                "special_instructions" : "String"
                "last_ip_address": "String"
                "considered_risky" : "Boolean",
                "products" :
                [
                    {
                        "product_id" : "Integer"
                        "product_name" : "String"
                        "description" : "String"
                        "price" : "Float"
                        "product_type" : "String"
                    }
                    {
                        "product_id" : "Integer"
                        "product_name" : "String"
                        "description" : "String"
                        "price" : "Float"
                        "product_type" : "String"
                    }
                ],
                "ship_address" :
                [
                    {
                        "id" : "Integer",
                        "firstname" : "String",
                        "lastname" : "String",
                        "address1" : "String",
                        "address2" : "String",
                        "city" : "String",
                        "zipcode" : "String",
                        "phone" : "String",
                        "state_name" : "String",
                        "alternative_phone" : "String",
                        "company" : "String",
                        "state_id" : "Integer",
                        "country_id" :"Integer",
                        "created_at" : "Timestamp",
                        "updated_at" : "Timestamp",
                        "sub_district'" : "String",
                        "delivery_instruction" : "String",
                        "preferences" : "String"
                    }
                    {
                        "id" : "Integer",
                        "firstname" : "String",
                        "lastname" : "String",
                        "address1" : "String",
                        "address2" : "String",
                        "city" : "String",
                        "zipcode" : "String",
                        "phone" : "String",
                        "state_name" : "String",
                        "alternative_phone" : "String",
                        "company" : "String",
                        "state_id" : "Integer",
                        "country_id" :"Integer",
                        "created_at" : "Timestamp",
                        "updated_at" : "Timestamp",
                        "sub_district'" : "String",
                        "delivery_instruction" : "String",
                        "preferences" : "String"
                    }
                     
                ],
                "adjustment":
                [
                    {
                        "adjustment_id": "Integer"
                        "source_type": "String"
                        "label": "String"
                        "amount": "Float"

                    }
                ]
                
            }
            }

+ Response 201 (application/json)
    + Attributes (CreationUpdateResponse)
    
    + Body
    
            {
                "code": "201"
                "successful_ids": "A151003"
            }

+ Response 401 (application/json)
    + Attributes (UnauthorizedResponse)
    
    + Body
    
            {
                "code": 403,
                "message": "Authorization header not found or invalid."
            }

### Update an Order [PUT]

+ Request (application/json)
    + Headers
        
            Accept: application/json
            Authorization: Basic base64-of-token:secret
        
    + Body
    
            {
                "id" : "123123h8913"
                "item_total" : "5"
                "total" : "20000"
                "state" : "1"
                "adjustment_total" : "1"
                "user_id" : "123ECFA123"
                "completed_at" : "2016-01-15 12:13:14"
                "payment_total" : "Double"
                "shipping_method_id" : "Integer"
                "shipment_state" : "String"
                "payment_state" : "String"
                "email" : "String"
                "special_instructions" : "String"
                "created_at" : "Timestamp"
                "updated_at" : "Timestamp"
                "currency" : "Symbol"
                "last_ip_address": "String"
                "shipment_total" : "Integer"
                "additional_tax_total" : "Integer"
                "promo_total" : "Integer"
                "item_count" : "invitation_tokenger"
                "confirmation_delivered" : Boolean"
                "considered_risky" : "Boolean",
                products :
                [
                    {
                        "id" : "ObjectID"
                        "name" : "String"
                        "description" : "String"
                        "price" : "Double"
                        "Type" : "String"
                    }
                    {
                        "id" : "ObjectID"
                        "name" : "String"
                        "description" : "String"
                        "price" : "Double"
                        "type" : "String"
                    }
                ]
                
                "ship_address_id" :
                [
                    {
                        "id" : "ObjectID",
                        "firstname" : "String",
                        "lastname" : "String",
                        "address1" : "String",
                        "address2" : "String",
                        "city" : "String",
                        "zipcode" : "String",
                        "phone" : "String",
                        "state_name" : "String",
                        "alternative_phone" : "String",
                        "company" : "String",
                        "state_id" : "Integer",
                        "country_id" :"Integer",
                        "created_at" : "Timestamp",
                        "updated_at" : "Timestamp",
                        "sub_district'" : "String",
                        "delivery_instruction" : "String",
                        "preferences" : "String"
                    }
                    {
                        "id" : "ObjectID",
                        "firstname" : "String",
                        "lastname" : "String",
                        "address1" : "String",
                        "address2" : "String",
                        "city" : "String",
                        "zipcode" : "String",
                        "phone" : "String",
                        "state_name" : "String",
                        "alternative_phone" : "String",
                        "company" : "String",
                        "state_id" : "Integer",
                        "country_id" :"Integer",
                        "created_at" : "Timestamp",
                        "updated_at" : "Timestamp",
                        "sub_district'" : "String",
                        "delivery_instruction" : "String",
                        "preferences" : "String"
                    }
                     
                ]
                
            }
            }

+ Response 201 (application/json)
    + Attributes (CreationUpdateResponse)
    
    + Body
    
            {
                "code": 201
                "successful_ids": "A151003"
               
            }

+ Response 401 (application/json)
    + Attributes (UnauthorizedResponse)
    
    + Body
    
            {
                "code": 403,
                "message": "Authorization header not found or invalid."
            }

## Single Order/Entry for Retrieving Fraud Percentage [/order/user/{user_id}]

+ Parameters
    + user_id (string) - ID of the order in the form of an integer / objectID 


### Get an Order [GET]
+ Request(application/json)
    
    + Headers
    
            Accept: application/json
            Authorization: Basic base64-of-token:secret

    + Body
    
            [
                {
                    "order_id": "A151601"
                }
            ]
    
+ Response 200 (application/json)

    + Body

            {
                "order_id": "A151601",
                "fraud_percentage": 25
            }

+ Response 401 (application/json)

    + Body
    
            {
                "code": 403,
                "message": "Authorization header not found or invalid."
            }

## Multiple Orders/Entries for Retrieving Fraud Percentage [/orders/user/{user_id}]

+ Parameters
    + user_id (string) - ID of the order in the form of an integer / objectID 


### Get an Order [GET]
+ Request(application/json)
    
    + Headers
    
            Accept: application/json
            Authorization: Basic base64-of-token:secret

    + Body
    
            [
                {
                    "order_id": "A151602"
                },
                {
                    "order_id": "A151603"
                },
                {
                    "order_id": "A151604"
                }
            ]
    
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "order_id": "A151602",
                    "fraud_percentage": 65
                },
                {
                    "order_id": "A151603",
                    "fraud_percentage": 35
                },
                {
                    "order_id": "A151604",
                    "fraud_percentage": 55
                }
            ]

+ Response 401 (application/json)

    + Body
    
            {
                "code": 403,
                "message": "Authorization header not found or invalid."
            }

# Data Structures

## Order (object)
+ order_id: A151003 (string, required) - The ID for an order/entry.

## ECFAOrder (Order)
+ fraud_percentage: 25 (number) - The fraud percentage of an order/entry.

## Response (object)
+ code: 200 (number, required) - The response's return code.

## CreationUpdateResponse (object)
+ code: 201 (number, required) - The response's return code.
+ successful_ids (array, required) - Collection of string denoting the order ID's which are successfuly made/updated.
    + A151003 (string) - The ID of the successfully made/updated order/entry.
+ unsuccessful_ids (array, required) - Collection of string denoting the order ID's which are failed to be made/updated.
    + B151003 (string) - The ID of the unsuccessfully made/update order/entry.

## UnauthorizedResponse (object)
+ code: 403 (number, required) - The response's return code.
+ message: Authorization header not found or invalid. (string, required) - The message denoting the error.